# Copyright © 2016 FENGberd.All rights reserved.
# GitHub Project:
# https://github.com/fengberd/FNPC

name: FNPC
main: FNPC\Main
version: 1.1.7
api: [1.0.0]
load: POSTWORLD
author: "FENGberd"
commands:
 fnpc:
  aliases: ["npc"]
  permission: FNPC.command.fnpc
  description: "NPC系統指令"
  usage: "使用 /fnpc help 查看幫助"
permissions:
 FNPC.*:
  description: "根權限"
  default: op
 FNPC.command.*:
  description: "使用命令權限"
  default: op
 FNPC.command.fnpc:
  description: "NPC命令使用權限"
  default: op

